name: Clojure CI

on:
  push:
    branches:
    - master

jobs:
  build:
 
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - name: build jar
      run: lein uberjar
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/forman.jar
        asset_name: forman.jar
        tag: ${{ github.ref }}
        overwrite: true
